"""Photosensor frequency check for ssvep-bci sessions."""

from photosensor_check.analysis import (
    Segment,
    Trial,
    build_trials,
    calibrate_sfreq,
    check_harmonics,
    detect_frame_skips,
    detect_peak,
    load_events,
    load_light_amp,
    load_psychopy_trials,
    load_stimuli,
    power_spectrum,
    retime_uniform,
    sampling_diagnostics,
    segment_trials,
    signal_quality,
    summarize,
    verify_alignment,
)

__all__ = [
    "Segment",
    "Trial",
    "build_trials",
    "calibrate_sfreq",
    "check_harmonics",
    "detect_frame_skips",
    "detect_peak",
    "load_events",
    "load_light_amp",
    "load_psychopy_trials",
    "load_stimuli",
    "power_spectrum",
    "retime_uniform",
    "sampling_diagnostics",
    "segment_trials",
    "signal_quality",
    "summarize",
    "verify_alignment",
]
